### PR TITLE
BREAKING CHANGE: Upgraded to NUnit 4

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`SIL.BuildTasks.Tests/ArchiveTests.cs` line 34 at r2](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66#-O9VZNeN8LWu6r2TihvF:-O9VZNeO-Pzvp300Btki:b-35c3xa) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/269f1071dc6571b03bfbd2562cce50126a950f82/SIL.BuildTasks.Tests/ArchiveTests.cs#L34)):*
> ```Smalltalk
> 		{
> 			var task = new Archive.Archive { Command = "Tar" };
> 			Assert.That(task.ExecutableName(), NUnit.Framework.Is.EqualTo("tar"));
> ```

Can't all these "NUnit.Framework."s be pulled up into the import?

You lose so much of the value of the Assert.That(A, Is.EqualtTo(B)) syntax with these in here.

**Comment by tombogle** [comment]
*[`SIL.BuildTasks.Tests/ArchiveTests.cs` line 34 at r2](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66#-O9VZNeN8LWu6r2TihvF:-O9WB1erCrMObaqUS-fH:b-896fix) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/269f1071dc6571b03bfbd2562cce50126a950f82/SIL.BuildTasks.Tests/ArchiveTests.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can't all these "NUnit.Framework."s be pulled up into the import?

You lose so much of the value of the Assert.That(A, Is.EqualtTo(B)) syntax with these in here.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 3 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`SIL.BuildTasks.Tests/UpdateBuildTypeFileTests.cs` line 19 at r3](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66#-OB7EFLn9G_jio9aFVDH:-OB7EFLn9G_jio9aFVDI:b-ois96f) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/501c904fb7a0c399dbe0bc64319849e3b0025eb9/SIL.BuildTasks.Tests/UpdateBuildTypeFileTests.cs#L19)):*
> ```Smalltalk
> 
> 			var types = UpdateBuildTypeFile.UpdateBuildTypeFile.GetVersionTypes(GetFileContentsForType("Alpha"));
> 			Assert.That(types, NUnit.Framework.Is.EquivalentTo(new [] {"Alpha", "Beta", "ReleaseCandidate", "Production"}));
> ```

A couple more `NUnit.Framework.`s in here...

Otherwise, LGTM

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @andrew-polk, @ermshiperete, and @jasonleenaylor)

___
*[`SIL.BuildTasks.Tests/UpdateBuildTypeFileTests.cs` line 19 at r3](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66#-OB7EFLn9G_jio9aFVDH:-OB7HUcL6-h1aA7aSBsS:b-896fix) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/501c904fb7a0c399dbe0bc64319849e3b0025eb9/SIL.BuildTasks.Tests/UpdateBuildTypeFileTests.cs#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

A couple more `NUnit.Framework.`s in here...

Otherwise, LGTM
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/66)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ermshiperete and @jasonleenaylor)

**Pull request merged**
