### PR TITLE
#62 Improved FileUpdate replacement verification and error handling

### PR DESCRIPTION
**Pull request by tombogle**
- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks like you need a changelog entry.

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63#-:-NbFxZqtE7J6ZUChva1a:bkt0yk8)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @tombogle)

___
*[`SIL.BuildTasks/FileUpdate.cs` line 51 at r2](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63#-NbFvSaK2bBzDBT1PLhi:-NbFvSaK2bBzDBT1PLhj:b-o0hz5k) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/fe1b351eda459db5cbca487701b1e778039882ad/SIL.BuildTasks/FileUpdate.cs#L51)):*
> ```Smalltalk
> 		}
> 
> 		internal string GetModifiedContents(string content, out bool success)
> ```

Do you think this is better?

internal bool TryGetModifiedContents(string content, out string modifiedContents)

If not, looks ok as is...

**Comment by tombogle** [comment]
*[`SIL.BuildTasks/FileUpdate.cs` line 51 at r2](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63#-NbFvSaK2bBzDBT1PLhi:-NbGa5bT42r8HDZSAw6v:bmmkzci) ([raw file](https://github.com/sillsdev/SIL.BuildTasks/blob/fe1b351eda459db5cbca487701b1e778039882ad/SIL.BuildTasks/FileUpdate.cs#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do you think this is better?

internal bool TryGetModifiedContents(string content, out string modifiedContents)

If not, looks ok as is...
</blockquote></details>

I reworked this in a much simpler way. (To me, the problem with Try... is that it implies that whether it succeeds or not, the result is equally acceptable, but in this case, failure really is an exception and will normally be treated as a build failure.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/SIL.BuildTasks/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

**Pull request merged**
